### PR TITLE
Reexport PrimE effect in Effectful.Monad

### PR DESCRIPTION
**Pull request by mmhat**

### CODE REVIEW

**Comment by arybczak** [comment]
Can you rename `PrimE` to `Prim`?

**Comment by mmhat** [comment]
Done.

**Comment by arybczak** [comment]
Thanks! You need to rebase over master though.

**Comment by mmhat** [comment]
Hm, bikeshedding: Do we want `Prim` or `Primitive`?

**Comment by arybczak** [comment]
I favor `Prim` because it's `MonadPrim` not `MonadPrimitive` :)

**Comment by arybczak** [comment]
Can you rebase over master and force push to the branch instead of merging new commits? Looks like GitHub got confused, the diff is unreadable.

**Comment by mmhat** [comment]
Ok, now the diffs look nice :slightly_smiling_face:

**Comment by arybczak** [comment]
Thanks :)

**Pull request merged**
